
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/helpFiles' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/CommonFiles' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/CommonFiles/lite' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/CommonFiles/plottingFunctions' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/CommonFiles/simulinkBased' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/Examples' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/Examples/Example_1.2-Bouncing_Ball_with_Lite_Simulator' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/Examples/Example_1.2a-Bouncing_Ball_with_simulink_External_files' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/Examples/Example_1.3-Bouncing_Ball_with_Input' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/Examples/Example_1.4-Bouncing_Ball_with_Simulink_operator_blocks' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/Examples/Example_1.5-Vehicle_on_Path_with_Boundaries' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/Examples/Example_1.6-Interconnection_of_Bouncing_Ball_and_Moving_Platform' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/Examples/Example_1.7-Synchronization_of_Fireflies' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/helpFiles/.Instructions_Main' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/CommonFiles/simulinkBased/Library' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/Examples/Example_1.8-A_Simple_Example' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/Examples/Example_1.8-A_Simple_Example/Ex1_8a_Jumps_Enforced' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/Examples/Example_1.8-A_Simple_Example/Ex1_8b_Flows_Enforced' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/Examples/Example_1.8-A_Simple_Example/Ex1_8c_Random_Rule' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/Examples/Example_1.8-A_Simple_Example/Ex1_8d_Solution_Outside_C_D' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/Examples/Example_1.8-A_Simple_Example/Ex1_8e_Solution_Reaches_Boundary_of_C' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/helpFiles/.Instructions_Main/Matlab2tex' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/helpFiles/.Instructions_Main/Matlab2tex_1_2' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/helpFiles/.Instructions_Main/Matlab2tex_1_3' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/helpFiles/.Instructions_Main/Matlab2tex_1_5' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/helpFiles/.Instructions_Main/Matlab2tex_1_6' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/helpFiles/.Instructions_Main/Matlab2tex_1_7' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/helpFiles/.Instructions_Main/macros' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/helpFiles/Matlab_Publish' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/helpFiles/Matlab_Publish/Html' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/helpFiles/Matlab_Publish/Html/html_HyEQSolver' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/helpFiles/Matlab_Publish/Html/html_plotHarc' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/helpFiles/Matlab_Publish/MatlabScripts' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/helpFiles/Matlab_Publish/MatlabScripts/Example_publish_template' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/helpFiles/Matlab_Publish/MatlabScripts/PlotHarc' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/helpFiles/Matlab_Publish/MatlabScripts/ex_1_2' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/helpFiles/Matlab_Publish/MatlabScripts/Example_publish_template/html' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/helpFiles/Matlab_Publish/MatlabScripts/PlotHarc/html' -begin
addpath '/home/rpichard/Documents/MATLAB/HyEQ_Toolbox_V2_02/helpFiles/Matlab_Publish/MatlabScripts/ex_1_2/html' -begin
